# GitHub Actions CI/CD - Build Yen for Windows, macOS, and Linux
# Copy this file to .github/workflows/ci-build.yml to activate
name: Build & Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            artifact: yen-linux-x64
          - os: macos-latest
            name: macOS
            artifact: yen-macos-arm64
          - os: windows-latest
            name: Windows
            artifact: yen-windows-x64

    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ── Linux dependencies ──
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libcurl4-openssl-dev

      # ── macOS dependencies ──
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake curl

      # ── Windows dependencies ──
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          vcpkg install curl:x64-windows

      # ── Build ──
      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --target yen

      # ── Package ──
      - name: Package (Linux)
        if: runner.os == 'Linux'
        run: |
          cd build
          cpack -G TGZ
          cpack -G DEB
          mkdir -p ../dist
          cp yen-*.tar.gz ../dist/ 2>/dev/null || true
          cp yen-*.deb ../dist/ 2>/dev/null || true

      - name: Package (macOS)
        if: runner.os == 'macOS'
        run: |
          cd build
          cpack -G TGZ
          mkdir -p ../dist
          cp yen-*.tar.gz ../dist/ 2>/dev/null || true
          # Create .pkg installer
          mkdir -p pkg_root/usr/local/bin
          mkdir -p pkg_root/usr/local/lib/yen/stdlib
          cp yen pkg_root/usr/local/bin/
          cp -r ../stdlib/* pkg_root/usr/local/lib/yen/stdlib/ 2>/dev/null || true
          pkgbuild --root pkg_root \
                   --identifier com.yen-lang.yen \
                   --version 1.1.0 \
                   --install-location / \
                   ../dist/yen-1.1.0-macos.pkg

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd build
          cpack -G ZIP -C Release
          mkdir -p ../dist
          Copy-Item yen-*.zip ../dist/ -ErrorAction SilentlyContinue
        shell: pwsh

      # ── Upload artifacts ──
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/*
          if-no-files-found: warn

  # ── Release ──
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
